### ISSUE TITLE
Infografía - Irving Zárate Reyes

### ISSUE THREAD

**Issue by Irvingzr16** [SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Irvingzr16#1]
[IZR- JavaScript y los contratos inteligentes.pdf](https://github.com/SistemasTecTlaxiaco/infografia-lenguajes-de-programacion-Irvingzr16/files/15135057/IZR-.JavaScript.y.los.contratos.inteligentes.pdf)

**Comment by Luz1727** [comment]
BUEN TRABAJO DESARROLLADO
BIEN ESTRUCTURADO CON BUENA INFORMACION 
20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
